version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg-fibonacci
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: websocket_fibonacci
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: websocket-fibonacci
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=postgres
      - DB_PASSWORD=senha123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=websocket_fibonacci
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata:


